import React from 'react';
import { 
  ChartPieSlice, 
  TrendUp, 
  TrendDown, 
  Warning, 
  CheckCircle, 
  Wallet, 
  Receipt, 
  ArrowRight,
  Bell,
  Gear,
  SquaresFour,
  FileText,
  Users,
  CaretRight,
  Lightning,
  DownloadSimple,
  Plus,
  Funnel,
  MagnifyingGlass,
  DotsThree,
  ArrowUpRight,
  ArrowDownLeft,
  CalendarBlank,
  User,
  Building,
  Clock,
  Printer,
  EnvelopeSimple,
  X,
  MagicWand,
  Sliders,
  ChartBar,
  Money,
  WarningCircle,
  PaperPlaneTilt
} from '@phosphor-icons/react';

// Re-exporting used icons for cleaner imports in components
export const Icons = {
  Dashboard: SquaresFour,
  Invoices: FileText,
  Cash: Wallet,
  Customers: Users,
  Settings: Gear,
  Notification: Bell,
  PieChart: ChartPieSlice,
  TrendUp,
  TrendDown,
  Warning,
  CheckCircle,
  Receipt,
  ArrowRight,
  CaretRight,
  Lightning,
  Download: DownloadSimple,
  Plus: Plus,
  Filter: Funnel,
  Search: MagnifyingGlass,
  More: DotsThree,
  Income: ArrowDownLeft,
  Expense: ArrowUpRight,
  Calendar: CalendarBlank,
  User: User,
  Building: Building,
  Clock,
  Printer,
  Envelope: EnvelopeSimple,
  Close: X,
  Forecast: MagicWand,
  Controls: Sliders,
  Chart: ChartBar,
  Money,
  Alert: WarningCircle,
  Send: PaperPlaneTilt
};